[package]
name = "solo5_hello"
version = "0.1.0"
authors = ["Nikita Nazarenko <savant.d@gmail.com>"]

[dependencies]
solo5 = { path = "/home/savant/devel/solo5/solo5-rs", features = ["ukvm"] }

[lib]
crate-type = ["staticlib"]
